### ISSUE TITLE
302 response

### ISSUE THREAD

**Issue by acflint** [abrom/rocketchat-ruby#26]
Hello! I'm running into an issue, which may just be my mistake. I'm running RC version 0.65.0.

Any request to the server returns a 302 response code. For example, I create a server with `ROCKET_SERVER = RocketChat::Server.new(ENV["ROCKET_URL"], debug: $stderr)` and when I try to login, or even get server info I get a 302 response. Such as `ROCKET_SERVER.info` returns `RocketChat::HTTPError: Invalid http response code: 302`. Do you have any suggestions to resolve that? Thanks!

**Comment by abrom** [comment]
It sounds like you have some sort of configuration issue..  What do you get if you request the `info` directly??

ie:

```
curl <your RC server schema & host>/api/v1/info
```

**Comment by acflint** [comment]
Hey @abrom, thanks for the super quick reply. I get `{"info":{"version":"0.65.0"},"success":true}` when I hit the API directly. The login, and all other calls work for me fine in AJAX or using Postman.

**Comment by abrom** [comment]
And how about:

```ruby
require 'rocketchat'

rocket_server = RocketChat::Server.new('http://your.server.address/')
puts rocket_server.info
```

**Comment by acflint** [comment]
`RocketChat::HTTPError: Invalid http response code: 302`

**Comment by acflint** [comment]
Oh! @abrom I think I found it. My server requires HTTPS. It seems to work with that. Sorry for bothering you!

**Comment by abrom** [comment]
That'll do it ;)
