### ISSUE TITLE
just not work

### ISSUE THREAD

**Issue by uranio-235** [abrom/rocketchat-ruby#4]
.3.3 :007 > rocket_server = RocketChat::Server.new('https://chat.hcg.sld.cu')
NameError: uninitialized constant RocketChat::RequestHelper::URI
	.. gems/rocketchat-0.1.3/lib/rocket_chat/request_helper.rb:20:in `server='
	... gems/ruby-2.3.3/gems/rocketchat-0.1.3/lib/rocket_chat/server.rb:16:in `initialize'

**Comment by abrom** [comment]
Thanks @uranio-235 

Problem was the URI module wasn't being loaded. This was being done automatically in the tests (and in my environment). Problem has been fixed here: https://github.com/abrom/rocketchat-ruby/commit/3a90f608d595a8b01d9b5a4b04a86589a02689b2  and released as gem v0.1.4
